// <auto-generated />
using System;
using CasePortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasePortal.Api.Migrations
{
    [DbContext(typeof(CasePortalDbContext))]
    partial class CasePortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasePortal.Api.Models.Company", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("");
                b.Property<DateOnly>("CreatedDate").HasColumnType("date");
                b.Property<bool>("IsActive").HasColumnType("bit").HasDefaultValue(true);
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("T_Company", (string)null);
            });

            modelBuilder.Entity("CasePortal.Api.Models.Membership", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<string>("CoInsurance").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("");
                b.Property<decimal>("CoPayment").HasColumnType("decimal(18,2)").HasDefaultValue(0m);
                b.Property<string>("Company").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasDefaultValue("");
                b.Property<DateOnly>("Date").HasColumnType("date");
                b.Property<decimal>("Deductible").HasColumnType("decimal(18,2)").HasDefaultValue(0m);
                b.Property<string>("Insurance").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("IdType").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("NRIC");
                b.Property<string>("IdNo").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)").HasDefaultValue("");
                b.Property<DateOnly?>("PolicyEffDate").HasColumnType("date");
                b.Property<DateOnly?>("PolicyExpDate").HasColumnType("date");
                b.Property<DateOnly?>("PolicyLapseDate").HasColumnType("date");
                b.Property<string>("PolicyNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("");
                b.Property<decimal>("RbEntitlement").HasColumnType("decimal(18,2)").HasDefaultValue(0m);
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("Inforce");
                b.Property<int?>("SubmissionId").HasColumnType("int");
                b.Property<string>("UnderwritingExclusion").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)").HasDefaultValue("");
                b.HasKey("Id");
                b.ToTable("T_Membership", (string)null);
            });

            modelBuilder.Entity("CasePortal.Api.Models.SubmissionGL", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<DateOnly?>("BillingDate").HasColumnType("date");
                b.Property<DateOnly>("CreatedDate").HasColumnType("date");
                b.Property<DateOnly?>("DateOfAdmission").HasColumnType("date");
                b.Property<DateOnly?>("DateOfDischarge").HasColumnType("date");
                b.Property<string>("DoctorName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)").HasDefaultValue("");
                b.Property<string>("DoctorSpecialty").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("");
                b.Property<decimal>("EstimatedCost").HasColumnType("decimal(18,2)").HasDefaultValue(0m);
                b.Property<int>("GlType").HasColumnType("int").HasDefaultValue(0);
                b.Property<string>("IcdCode").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("");
                b.Property<int>("MembershipId").HasColumnType("int");
                b.Property<string>("Mrn").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("");
                b.Property<string>("ProvisionalDiagnosis").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)").HasDefaultValue("");
                b.Property<string>("RequestType").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("");
                b.Property<string>("SubmissionStatus").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("");
                b.HasKey("Id");
                b.HasIndex("MembershipId");
                b.ToTable("T_SubmissionGL", (string)null);
            });

            modelBuilder.Entity("CasePortal.Api.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                b.Property<int?>("CompanyId").HasColumnType("int");
                b.Property<DateOnly>("CreatedDate").HasColumnType("date");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasColumnType("bit").HasDefaultValue(true);
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasDefaultValue("User");
                b.HasKey("Id");
                b.HasIndex("CompanyId");
                b.HasIndex("Email").IsUnique();
                b.ToTable("T_User", (string)null);
            });

            modelBuilder.Entity("CasePortal.Api.Models.SubmissionGL", b =>
            {
                b.HasOne("CasePortal.Api.Models.Membership", null)
                    .WithMany()
                    .HasForeignKey("MembershipId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CasePortal.Api.Models.User", b =>
            {
                b.HasOne("CasePortal.Api.Models.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
        }
    }
}
